feat: insert shapefile mime types
axone-protocol/ontology pull request #88
Opened 2023-03-16 15:46 UTC by CedrickArmel

feat: insert shapefile mime types

I have inserted `application/x-shapefile` and `application/x-gis`  both MIME types for the ``shapefile`` format (``.shp`` ). The shapefile format is a geospatial vector data format for geographic information system (GIS) software.

See more [here](https://en.wikipedia.org/wiki/Shapefile).

2023-03-17 09:33 UTC, henigh commented
> feat: insert shapefile mime types
> 
> I have inserted `application/x-shapefile` and `application/x-gis` both MIME types for the `shapefile` format (`.shp` ). The shapefile format is a geospatial vector data format for geographic information system (GIS) software.
> 
> See more [here](https://en.wikipedia.org/wiki/Shapefile).

@CedrickArmel 
FYI "Shapefile" is a set of files linked together to define a vector geographical data format.
`.shp` in one of the **3 mandatory files** for the shapefile data format, which are : 
- `.shp` : feature geometry
- `.shx` : index of feature geometry
- `.dbf` :  attribute information

Optional files : (includes but not limited to...)
- `.prj` : coordinate system and projection information in well-known text, or WKT, format)
- `.idx`  : Indexing file, same file format is used by ESRI)
- `.sbn` and `.sbx` : spatial index
- `.shp.xml` : **geospatial metadata** in XML format
- `.cpg` : code page files

2023-03-17 12:41 UTC, ccamel commented
Agree with @henigh. And from what I see, the media types to use for shapefiles are:
- `application/vnd.shp` for `.shp` (feature geometry) - see: https://www.iana.org/assignments/media-types/application/vnd.shp
- `application/vnd.shx` for `.shx` (index of feature geometry) - see: https://www.iana.org/assignments/media-types/application/vnd.shx
- `application/vnd.dbf` for `.dbf` (attribute information) - see: https://www.iana.org/assignments/media-types/application/vnd.dbf

2023-03-30 07:05 UTC, MdechampG approved these changes

2023-03-30 12:59 UTC, ccamel requested changes
Some typos. I don't understand why the CI actions didn't run. The build should have reported ther errors.

2023-03-30 19:54 UTC, CedrickArmel commented
@ccamel  Do you use an RDF/RDFS/OWL linter should i install ? I haven't seen any lint requirements in the project.

2023-03-31 07:25 UTC, ccamel commented
> @ccamel Do you use an RDF/RDFS/OWL serializations linter should i install ? I haven't seen any lint requirements in the project.

They are. See [.github/workflows/lint.yml](ttps://github.com/okp4/ontology/blob/main/.github/workflows/lint.yml) github CI workflows.

But at least, your project must build:

```sh
make build
```

Additionally, a linter is present that checks the correct formatting of `turtle` files, and it can be executed using the following command:

```sh
make lint-ttl
```

However, right now it fails due to https://github.com/atextor/owl-cli/issues/8.

2026-08-20 17:11 UTC, ccamel commented
ooops, this PR has been open for quite a while. 😅 time to do a bit of cleanup.

FI the media-type vocabulary will likely be deprecated soon, as the ontology is now focused more on schemas for verifiable credentials used in on-chain governance decisions. Adding shapefile-specific terms is therefore no longer relevant.

Thanks a lot for the proposal!

2026-08-20 17:11 UTC, closed without merging